-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_in_stream_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    data_in_stream_TVALID : IN STD_LOGIC;
    data_in_stream_TREADY : OUT STD_LOGIC;
    data_out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_out_stream_TVALID : OUT STD_LOGIC;
    data_out_stream_TREADY : IN STD_LOGIC );
end;


architecture behav of FIR_filter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FIR_filter_FIR_filter,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010i-clg225-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.944600,HLS_SYN_LAT=33,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3781,HLS_SYN_LUT=1751,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_2 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_3 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_4 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_5 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_6 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_7 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_8 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_9 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_10 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_11 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_12 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_13 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_14 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_15 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_16 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_17 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_18 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_19 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_20 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_21 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_22 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_23 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_24 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_25 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_26 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_27 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_28 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_29 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_30 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_31 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_32 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_33 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_34 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_35 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_36 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_37 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_38 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_39 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_40 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_41 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_42 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_43 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_44 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_45 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_46 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_47 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_48 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_49 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_50 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_51 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_52 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal data_in_stream_TDATA_blk_n : STD_LOGIC;
    signal data_out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_122_reg_1052 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_123_reg_1057 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_124_reg_1062 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_125_reg_1067 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_126_reg_1072 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_127_reg_1077 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_128_reg_1082 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_129_reg_1087 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_130_reg_1092 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_131_reg_1097 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_132_reg_1102 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_133_reg_1107 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_134_reg_1112 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_135_reg_1117 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_136_reg_1122 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_137_reg_1127 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_138_reg_1132 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_139_reg_1137 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_140_reg_1142 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_141_reg_1147 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_142_reg_1152 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_143_reg_1157 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_144_reg_1162 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_145_reg_1167 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_146_reg_1172 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_147_reg_1177 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_148_reg_1182 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_149_reg_1187 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_150_reg_1192 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_151_reg_1197 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_152_reg_1202 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_153_reg_1207 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_154_reg_1212 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_155_reg_1217 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_156_reg_1222 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_157_reg_1227 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_158_reg_1232 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_159_reg_1237 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_160_reg_1242 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_161_reg_1247 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_162_reg_1252 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_163_reg_1257 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_164_reg_1262 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_165_reg_1267 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_166_reg_1272 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_167_reg_1277 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_168_reg_1282 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_169_reg_1287 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_170_reg_1292 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_171_reg_1297 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_172_reg_1302 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_173_reg_1307 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_174_reg_1312 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_load_reg_1317 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1_load_reg_1322 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2_load_reg_1327 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3_load_reg_1332 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4_load_reg_1337 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5_load_reg_1342 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6_load_reg_1347 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7_load_reg_1352 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8_load_reg_1357 : STD_LOGIC_VECTOR (23 downto 0);
    signal FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9_load_reg_1362 : STD_LOGIC_VECTOR (23 downto 0);
    signal data_in_stream_read_reg_1367 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_lhs_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_lhs_V_out_ap_vld : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_lhs_V_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_lhs_V_1_out_ap_vld : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_lhs_V_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_lhs_V_2_out_ap_vld : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_lhs_V_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_lhs_V_3_out_ap_vld : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_total_fu_300_ap_start : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_total_fu_300_ap_done : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_total_fu_300_ap_idle : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_total_fu_300_ap_ready : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_total_fu_300_total_V_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FIR_filter_Pipeline_total_fu_300_total_V_2_out_ap_vld : STD_LOGIC;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call137 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call139 : BOOLEAN;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call141 : BOOLEAN;
    signal grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call143 : BOOLEAN;
    signal grp_FIR_filter_Pipeline_total_fu_300_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal regslice_both_data_out_stream_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_data_in_stream_U_apdone_blk : STD_LOGIC;
    signal data_in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal data_in_stream_TVALID_int_regslice : STD_LOGIC;
    signal data_in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_data_in_stream_U_ack_in : STD_LOGIC;
    signal data_out_stream_TVALID_int_regslice : STD_LOGIC;
    signal data_out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_data_out_stream_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1_load : IN STD_LOGIC_VECTOR (23 downto 0);
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_load : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_105 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_104 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_103 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_102 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_101 : IN STD_LOGIC_VECTOR (23 downto 0);
        lhs_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_out_ap_vld : OUT STD_LOGIC );
    end component;


    component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_100 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_99 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_98 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_97 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_96 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_95 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_94 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_93 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_92 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_91 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_90 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_89 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_88 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_87 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_86 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_85 : IN STD_LOGIC_VECTOR (23 downto 0);
        lhs_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_12 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_84 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_83 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_82 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_81 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_80 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_79 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_78 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_77 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_76 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_75 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_74 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_73 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_72 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_71 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_70 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_69 : IN STD_LOGIC_VECTOR (23 downto 0);
        lhs_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_13 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_68 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_67 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_66 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_65 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_64 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_63 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_62 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_61 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_60 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_59 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_58 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_57 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_56 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_55 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_54 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_53 : IN STD_LOGIC_VECTOR (23 downto 0);
        lhs_V_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_3_out_ap_vld : OUT STD_LOGIC );
    end component;


    component FIR_filter_FIR_filter_Pipeline_total IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lhs_V_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        lhs_V_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        total_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        total_V_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component FIR_filter_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207 : component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start,
        ap_done => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_ready,
        empty => data_in_stream_read_reg_1367,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9_load_reg_1362,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8_load_reg_1357,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7_load_reg_1352,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6_load_reg_1347,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5_load_reg_1342,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4_load_reg_1337,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3_load_reg_1332,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2_load_reg_1327,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1_load_reg_1322,
        FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_load => FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_load_reg_1317,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_105 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_174_reg_1312,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_104 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_173_reg_1307,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_103 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_172_reg_1302,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_102 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_171_reg_1297,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_101 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_170_reg_1292,
        lhs_V_out => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_lhs_V_out,
        lhs_V_out_ap_vld => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_lhs_V_out_ap_vld);

    grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231 : component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start,
        ap_done => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_ready,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_100 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_169_reg_1287,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_99 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_168_reg_1282,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_98 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_167_reg_1277,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_97 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_166_reg_1272,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_96 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_165_reg_1267,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_95 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_164_reg_1262,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_94 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_163_reg_1257,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_93 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_162_reg_1252,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_92 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_161_reg_1247,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_91 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_160_reg_1242,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_90 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_159_reg_1237,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_89 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_158_reg_1232,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_88 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_157_reg_1227,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_87 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_156_reg_1222,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_86 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_155_reg_1217,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_85 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_154_reg_1212,
        lhs_V_1_out => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_lhs_V_1_out,
        lhs_V_1_out_ap_vld => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_lhs_V_1_out_ap_vld);

    grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254 : component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_12
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start,
        ap_done => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_ready,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_84 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_153_reg_1207,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_83 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_152_reg_1202,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_82 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_151_reg_1197,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_81 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_150_reg_1192,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_80 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_149_reg_1187,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_79 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_148_reg_1182,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_78 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_147_reg_1177,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_77 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_146_reg_1172,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_76 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_145_reg_1167,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_75 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_144_reg_1162,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_74 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_143_reg_1157,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_73 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_142_reg_1152,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_72 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_141_reg_1147,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_71 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_140_reg_1142,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_70 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_139_reg_1137,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_69 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_138_reg_1132,
        lhs_V_2_out => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_lhs_V_2_out,
        lhs_V_2_out_ap_vld => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_lhs_V_2_out_ap_vld);

    grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277 : component FIR_filter_FIR_filter_Pipeline_VITIS_LOOP_49_13
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start,
        ap_done => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_ready,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_68 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_137_reg_1127,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_67 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_136_reg_1122,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_66 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_135_reg_1117,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_65 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_134_reg_1112,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_64 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_133_reg_1107,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_63 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_132_reg_1102,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_62 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_131_reg_1097,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_61 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_130_reg_1092,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_60 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_129_reg_1087,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_59 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_128_reg_1082,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_58 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_127_reg_1077,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_57 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_126_reg_1072,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_56 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_125_reg_1067,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_55 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_124_reg_1062,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_54 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_123_reg_1057,
        p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_53 => p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_122_reg_1052,
        lhs_V_3_out => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_lhs_V_3_out,
        lhs_V_3_out_ap_vld => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_lhs_V_3_out_ap_vld);

    grp_FIR_filter_Pipeline_total_fu_300 : component FIR_filter_FIR_filter_Pipeline_total
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_FIR_filter_Pipeline_total_fu_300_ap_start,
        ap_done => grp_FIR_filter_Pipeline_total_fu_300_ap_done,
        ap_idle => grp_FIR_filter_Pipeline_total_fu_300_ap_idle,
        ap_ready => grp_FIR_filter_Pipeline_total_fu_300_ap_ready,
        lhs_V_reload => grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_lhs_V_out,
        lhs_V_1_reload => grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_lhs_V_1_out,
        lhs_V_2_reload => grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_lhs_V_2_out,
        lhs_V_3_reload => grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_lhs_V_3_out,
        total_V_2_out => grp_FIR_filter_Pipeline_total_fu_300_total_V_2_out,
        total_V_2_out_ap_vld => grp_FIR_filter_Pipeline_total_fu_300_total_V_2_out_ap_vld);

    regslice_both_data_in_stream_U : component FIR_filter_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => data_in_stream_TDATA,
        vld_in => data_in_stream_TVALID,
        ack_in => regslice_both_data_in_stream_U_ack_in,
        data_out => data_in_stream_TDATA_int_regslice,
        vld_out => data_in_stream_TVALID_int_regslice,
        ack_out => data_in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_data_in_stream_U_apdone_blk);

    regslice_both_data_out_stream_U : component FIR_filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_FIR_filter_Pipeline_total_fu_300_total_V_2_out,
        vld_in => data_out_stream_TVALID_int_regslice,
        ack_in => data_out_stream_TREADY_int_regslice,
        data_out => data_out_stream_TDATA,
        vld_out => regslice_both_data_out_stream_U_vld_out,
        ack_out => data_out_stream_TREADY,
        apdone_blk => regslice_both_data_out_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FIR_filter_Pipeline_total_fu_300_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_FIR_filter_Pipeline_total_fu_300_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_FIR_filter_Pipeline_total_fu_300_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FIR_filter_Pipeline_total_fu_300_ap_ready = ap_const_logic_1)) then 
                    grp_FIR_filter_Pipeline_total_fu_300_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9 <= data_in_stream_TDATA_int_regslice;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_1;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_1 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_2;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_10 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_11;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_11 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_12;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_12 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_13;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_13 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_14;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_14 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_15;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_15 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_16;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_16 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_17;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_17 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_18;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_18 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_19;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_19 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_20;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_2 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_3;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_20 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_21;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_21 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_22;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_22 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_23;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_23 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_24;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_24 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_25;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_25 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_26;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_26 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_27;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_27 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_28;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_28 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_29;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_29 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_30;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_3 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_4;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_30 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_31;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_31 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_32;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_32 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_33;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_33 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_34;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_34 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_35;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_35 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_36;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_36 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_37;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_37 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_38;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_38 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_39;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_39 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_40;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_4 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_5;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_40 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_41;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_41 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_42;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_42 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_43;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_43 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_44;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_44 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_45;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_45 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_46;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_46 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_47;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_47 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_48;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_48 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_49;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_49 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_50;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_5 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_6;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_50 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_51;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_51 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_52;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_52 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_6 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_7;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_7 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_8;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_8 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_9;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_9 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1_load_reg_1322 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_1;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2_load_reg_1327 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_2;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3_load_reg_1332 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_3;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4_load_reg_1337 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_4;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5_load_reg_1342 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_5;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6_load_reg_1347 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_6;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7_load_reg_1352 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_7;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8_load_reg_1357 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_8;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9_load_reg_1362 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_9;
                FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg_load_reg_1317 <= FIR_filter_stream_stream_ap_fixed_32_7_4_0_1_0_fir_shift_reg;
                data_in_stream_read_reg_1367 <= data_in_stream_TDATA_int_regslice;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_122_reg_1052 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_123_reg_1057 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_1;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_124_reg_1062 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_2;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_125_reg_1067 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_3;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_126_reg_1072 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_4;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_127_reg_1077 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_5;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_128_reg_1082 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_6;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_129_reg_1087 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_7;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_130_reg_1092 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_8;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_131_reg_1097 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_9;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_132_reg_1102 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_10;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_133_reg_1107 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_11;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_134_reg_1112 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_12;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_135_reg_1117 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_13;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_136_reg_1122 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_14;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_137_reg_1127 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_15;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_138_reg_1132 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_16;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_139_reg_1137 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_17;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_140_reg_1142 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_18;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_141_reg_1147 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_19;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_142_reg_1152 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_20;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_143_reg_1157 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_21;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_144_reg_1162 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_22;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_145_reg_1167 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_23;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_146_reg_1172 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_24;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_147_reg_1177 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_25;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_148_reg_1182 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_26;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_149_reg_1187 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_27;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_150_reg_1192 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_28;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_151_reg_1197 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_29;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_152_reg_1202 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_30;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_153_reg_1207 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_31;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_154_reg_1212 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_32;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_155_reg_1217 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_33;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_156_reg_1222 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_34;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_157_reg_1227 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_35;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_158_reg_1232 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_36;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_159_reg_1237 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_37;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_160_reg_1242 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_38;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_161_reg_1247 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_39;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_162_reg_1252 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_40;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_163_reg_1257 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_41;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_164_reg_1262 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_42;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_165_reg_1267 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_43;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_166_reg_1272 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_44;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_167_reg_1277 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_45;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_168_reg_1282 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_46;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_169_reg_1287 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_47;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_170_reg_1292 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_48;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_171_reg_1297 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_49;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_172_reg_1302 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_50;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_173_reg_1307 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_51;
                p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_174_reg_1312 <= p_ZZ10FIR_filterRN3hls6streamI8ap_fixedILi24ELi1EL9ap_q_mode4EL9ap_o_mode0ELi1EEL_52;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state6, grp_FIR_filter_Pipeline_total_fu_300_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, regslice_both_data_out_stream_U_apdone_blk, ap_block_state2_on_subcall_done, data_in_stream_TVALID_int_regslice, data_out_stream_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_FIR_filter_Pipeline_total_fu_300_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((data_out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((data_out_stream_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_data_out_stream_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, data_in_stream_TVALID_int_regslice)
    begin
        if (((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_FIR_filter_Pipeline_total_fu_300_ap_done)
    begin
        if ((grp_FIR_filter_Pipeline_total_fu_300_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(data_out_stream_TREADY_int_regslice)
    begin
        if ((data_out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(regslice_both_data_out_stream_U_apdone_blk, data_out_stream_TREADY_int_regslice)
    begin
        if (((data_out_stream_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_data_out_stream_U_apdone_blk = ap_const_logic_1))) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, data_in_stream_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call137_assign_proc : process(ap_start, data_in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call137 <= ((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call139_assign_proc : process(ap_start, data_in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call139 <= ((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call141_assign_proc : process(ap_start, data_in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call141 <= ((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call143_assign_proc : process(ap_start, data_in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call143 <= ((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_done, grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_done, grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_done, grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_done = ap_const_logic_0) or (grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_done = ap_const_logic_0) or (grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_done = ap_const_logic_0) or (grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_done = ap_const_logic_0));
    end process;


    ap_block_state6_assign_proc : process(regslice_both_data_out_stream_U_apdone_blk, data_out_stream_TREADY_int_regslice)
    begin
                ap_block_state6 <= ((data_out_stream_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_data_out_stream_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, regslice_both_data_out_stream_U_apdone_blk, data_out_stream_TREADY_int_regslice)
    begin
        if ((not(((data_out_stream_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_data_out_stream_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_data_out_stream_U_apdone_blk, data_out_stream_TREADY_int_regslice)
    begin
        if ((not(((data_out_stream_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_data_out_stream_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    data_in_stream_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, data_in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            data_in_stream_TDATA_blk_n <= data_in_stream_TVALID_int_regslice;
        else 
            data_in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    data_in_stream_TREADY <= regslice_both_data_in_stream_U_ack_in;

    data_in_stream_TREADY_int_regslice_assign_proc : process(ap_start, ap_CS_fsm_state1, data_in_stream_TVALID_int_regslice)
    begin
        if ((not(((data_in_stream_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            data_in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            data_in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    data_out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, data_out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            data_out_stream_TDATA_blk_n <= data_out_stream_TREADY_int_regslice;
        else 
            data_out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    data_out_stream_TVALID <= regslice_both_data_out_stream_U_vld_out;

    data_out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state5, data_out_stream_TREADY_int_regslice)
    begin
        if (((data_out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            data_out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            data_out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start <= grp_FIR_filter_Pipeline_VITIS_LOOP_49_11_fu_231_ap_start_reg;
    grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start <= grp_FIR_filter_Pipeline_VITIS_LOOP_49_12_fu_254_ap_start_reg;
    grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start <= grp_FIR_filter_Pipeline_VITIS_LOOP_49_13_fu_277_ap_start_reg;
    grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start <= grp_FIR_filter_Pipeline_VITIS_LOOP_49_1_fu_207_ap_start_reg;
    grp_FIR_filter_Pipeline_total_fu_300_ap_start <= grp_FIR_filter_Pipeline_total_fu_300_ap_start_reg;
end behav;
